export const CONFIG = {
  render: {
    background: '#091120',
    fogNear: 130,
    fogFar: 330,
    maxPixelRatio: 1.75,
  },
  simulation: {
    step: 1 / 60,
    maxFrameTime: 0.25,
    maxSubsteps: 5,
  },
  world: {
    arenaRadius: 180,
    chunkSize: 72,
    activeChunkRadius: 2,
    seaLevel: -2,
    minAltitude: 7,
    maxAltitude: 82,
    mountainRingRadius: 150,
    spawnMinDistance: 56,
    spawnMaxDistance: 155,
    enemyDespawnDistance: 280,
  },
  player: {
    maxHealth: 100,
    thrust: 44,
    reverseThrust: 26,
    strafe: 30,
    vertical: 25,
    yawSpeed: 1.95,
    fireCooldown: 0.13,
    projectileSpeed: 155,
    projectileLife: 2.6,
    projectileTurnRate: 9.5,
    spreadAngle: 0.14,
    overdriveFireCooldown: 0.075,
    radius: 2.5,
    collisionRadius: 2.8,
    invulnerabilityTime: 0.85,
    pulseCooldown: 10,
    pulseRadius: 24,
    pulseDamage: 24,
  },
  projectiles: {
    maxCount: 240,
    playerDamage: 20,
    enemyDamage: 10,
  },
  audio: {
    masterVolume: 0.45,
    distanceRef: 18,
    distanceMax: 180,
    lowHealthThreshold: 25,
    enginePitchRange: {
      min: 0.85,
      max: 1.4,
    },
  },
  enemies: {
    tank: {
      health: 32,
      moveSpeed: 9,
      fireInterval: 2.3,
      projectileSpeed: 56,
      projectileLife: 3.8,
      score: 110,
      radius: 3.7,
      damage: 12,
    },
    drone: {
      health: 24,
      moveSpeed: 20,
      fireInterval: 1.7,
      projectileSpeed: 80,
      projectileLife: 2.8,
      score: 150,
      radius: 3.2,
      damage: 10,
    },
    missile: {
      health: 10,
      moveSpeed: 42,
      turnRate: 3.2,
      score: 90,
      radius: 2.1,
      damage: 20,
      life: 5.5,
    },
    turret: {
      health: 34,
      fireInterval: 1.6,
      projectileSpeed: 78,
      projectileLife: 2.9,
      score: 165,
      radius: 3.4,
      damage: 12,
    },
    ship: {
      health: 46,
      fireInterval: 3.6,
      projectileSpeed: 48,
      projectileLife: 4.5,
      score: 220,
      radius: 5.8,
      damage: 18,
    },
    boss: {
      health: 220,
      fireInterval: 2.1,
      missileInterval: 5.4,
      projectileSpeed: 62,
      projectileLife: 4.8,
      score: 1200,
      radius: 10.5,
      damage: 16,
    },
  },
  waves: {
    spawnInterval: 0.8,
    interWaveDelay: 2.4,
    softTimeout: 34,
    maxConcurrent: {
      tank: 6,
      drone: 7,
      missile: 4,
      turret: 3,
      ship: 3,
      boss: 1,
    },
  },
  palette: {
    player: 0x8af4ff,
    playerAccent: 0xffd166,
    tank: 0x9bb37d,
    drone: 0xff8865,
    missile: 0xff5f5f,
    turret: 0xffc857,
    ship: 0x52c2c8,
    boss: 0x9fe6ff,
    hostileShot: 0xffb86c,
    playerShot: 0x8af4ff,
    terrain: 0x516d4b,
    sea: 0x0d3e70,
    mountain: 0x718c61,
    effect: 0xffd7a3,
    hazard: 0xb880ff,
    pickup: {
      repair: 0xff5f6d,
      overdrive: 0xffd166,
      spread: 0x8af4ff,
      shield: 0xc78aff,
    },
  },
  effects: {
    shake: {
      maxDisplacement: 1.2,
      onDamage: { intensity: 0.8, duration: 0.3 },
      onKill: { intensity: 0.5, duration: 0.2 },
      onFire: { intensity: 0.15, duration: 0.08 },
    },
    hitIndicator: {
      fadeIn: 0.05,
      hold: 0.15,
      fadeOut: 0.3,
      chevronRadius: 120,
    },
    explosion: {
      poolSize: 15,
      fireballDuration: 0.6,
      debrisCount: 4,
      debrisDuration: 1.5,
      debrisFadeTime: 0.3,
      debrisGravity: 18,
      debrisSpeed: 12,
    },
    muzzleFlash: {
      duration: 0.06,
      lightIntensity: 3.0,
      lightRange: 15,
    },
    trail: {
      lightIntensity: 0.6,
      lightRange: 8,
      trackingWidthMultiplier: 1.5,
      trackingBrightnessBoost: 0.4,
    },
    scorePop: {
      poolSize: 10,
      riseSpeed: 5,
      duration: 1.0,
      startScale: 0.8,
      endScale: 1.3,
      fontSize: 48,
    },
  },
  powerUps: {
    life: 12,
    bobSpeed: 2.1,
    collectionRadius: 5.4,
    timedDuration: 10,
    shieldDuration: 8,
    repairAmount: 34,
    maxActive: 4,
    spawnIntervalMin: 5.5,
    spawnIntervalMax: 9.5,
    spawnDistanceMin: 34,
    spawnDistanceMax: 118,
    types: ['repair', 'overdrive', 'spread', 'shield'],
    weights: {
      repair: 4,
      overdrive: 2,
      spread: 2,
      shield: 2,
    },
  },
  hazards: {
    dps: 12,
    duration: 12,
    radius: 12,
    tickInterval: 0.35,
  },
};
